### ISSUE TITLE
能保存mp4文件到相册吗？

### ISSUE THREAD

**Issue by aaaking** [hushenghao/MediaStoreDemo#2]
能保存mp4文件到相册吗？

**Comment by hushenghao** [comment]
同理，只是换一下Uri和文件路径

**Comment by aaaking** [comment]
> 

MediaStore.Video.Media和 MediaStore.Images.Media数据库的列名都一样吗？都一样的话应该只把MediaStore.Images.Media.getContentUri换成MediaStore.Video.Media.getContentUri就行了吧？

**Comment by hushenghao** [comment]
这个需要你自己验证
